name: Build and Publish Docker Image to DockerHub

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: DockerHub Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file build/docker/prod/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/trasa

      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/trasa